package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/internal/gorm/dbal/models"
)

// (C)RUD: projects
// Generated/AI values are passed to DTO/model.

var CreateProject = func(ctx context.Context, item *models.Project) error {
	ds := DS(ctx)
	return ds.Create(ctx, "projects", item)
}

// C(R)UD: projects

var ReadProjectList = func(ctx context.Context) (res []*models.Project, err error) {
	ds := DS(ctx)
	err = ds.ReadAll(ctx, "projects", &res)
	return
}

// C(R)UD: projects

var ReadProject = func(ctx context.Context, pID int64) (*models.Project, error) {
	ds := DS(ctx)
	res := &models.Project{}
	err := ds.Read(ctx, "projects", res, pID)
	if err == nil {
		return res, nil
	}
	return nil, err
}

// CR(U)D: projects

var UpdateProject = func(ctx context.Context, item *models.Project) (rowsAffected int64, err error) {
	ds := DS(ctx)
	rowsAffected, err = ds.Update(ctx, "projects", item)
	return
}

// CRU(D): projects

var DeleteProject = func(ctx context.Context, item *models.Project) (rowsAffected int64, err error) {
	ds := DS(ctx)
	rowsAffected, err = ds.Delete(ctx, "projects", item)
	return
}

var ReadAllRaw = func(ctx context.Context) (res []*models.ProjectLi, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.Select(ctx, sql, &res)
	return
}

var GetProjectIds = func(ctx context.Context) (res []int64, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.QueryAll(ctx, sql, &res)
	return
}

var GetProjectID = func(ctx context.Context) (res int64, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.Query(ctx, sql, &res)
	return
}
