package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/internal/gorm/dbal/models"
)

// (C)RUD: tasks
// Generated/AI values are passed to DTO/model.

var CreateTask = func(ctx context.Context, item *models.Task) error {
	ds := DS(ctx)
	return ds.Create(ctx, "tasks", item)
}

// C(R)UD: tasks

var ReadTaskList = func(ctx context.Context) (res []*models.Task, err error) {
	ds := DS(ctx)
	err = ds.ReadAll(ctx, "tasks", &res)
	return
}

// C(R)UD: tasks

var ReadTask = func(ctx context.Context, tID int64) (*models.Task, error) {
	ds := DS(ctx)
	res := &models.Task{}
	err := ds.Read(ctx, "tasks", res, tID)
	if err == nil {
		return res, nil
	}
	return nil, err
}

// CR(U)D: tasks

var UpdateTask = func(ctx context.Context, item *models.Task) (rowsAffected int64, err error) {
	ds := DS(ctx)
	rowsAffected, err = ds.Update(ctx, "tasks", item)
	return
}

// CRU(D): tasks

var DeleteTask = func(ctx context.Context, item *models.Task) (rowsAffected int64, err error) {
	ds := DS(ctx)
	rowsAffected, err = ds.Delete(ctx, "tasks", item)
	return
}

var RawProjectTasks = func(ctx context.Context, pID int64) (res []*models.TaskLi, err error) {
	ds := DS(ctx)
	sql := `select t_id, t_priority, t_date, t_subject from tasks where p_id =? 
		order by t_id`
	err = ds.Select(ctx, sql, &res, pID)
	return
}
