package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/internal/no_orm/dbal/dto"
)

// (C)RUD: projects
// Generated/AI values are passed to DTO/model.

var CreateProject = func(ctx context.Context, item *dto.Project) error {
	ds := DS(ctx)
	sql := `insert into projects (p_name) values (?)`
	row, err := ds.Insert(ctx, sql, "p_id", item.PName)
	if err == nil {
		err = SetRes(&item.PID, row)
	}
	return err
}

// C(R)UD: projects

var ReadProject = func(ctx context.Context, pID int64) (*dto.Project, error) {
	ds := DS(ctx)
	sql := `select * from projects where p_id=?`
	row, err := ds.QueryRow(ctx, sql, pID)
	if err != nil {
		return nil, err
	}
	item := dto.Project{}
	errMap := make(map[string]int)
	SetInt64(&item.PID, row, "p_id", errMap)
	SetString(&item.PName, row, "p_name", errMap)
	err = ErrMapToErr(errMap)
	return &item, err
}

// CR(U)D: projects

var UpdateProject = func(ctx context.Context, item *dto.Project) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `update projects set p_name=? where p_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.PName, item.PID)
	return
}

// CRU(D): projects

var DeleteProject = func(ctx context.Context, item *dto.Project) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `delete from projects where p_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.PID)
	return
}

var ReadAll = func(ctx context.Context) (res []*dto.ProjectLi, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	errMap := make(map[string]int)
	_onRow := func(row map[string]interface{}) {
		item := dto.ProjectLi{}
		SetInt64(&item.PID, row, "p_id", errMap)
		SetString(&item.PName, row, "p_name", errMap)
		SetAny(&item.PTasksCount, row, "p_tasks_count", errMap)
		res = append(res, &item)
	}
	err = ds.QueryAllRows(ctx, sql, _onRow)
	if err == nil {
		err = ErrMapToErr(errMap)
	}
	return
}

var GetProjectIds = func(ctx context.Context) (res []int64, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.QueryAll(ctx, sql, &res)
	return
}

var GetProjectID = func(ctx context.Context) (res []int64, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.QueryAll(ctx, sql, &res)
	return
}

var PID = func(ctx context.Context) (res int64, err error) {
	ds := DS(ctx)
	sql := `select * from projects`
	err = ds.Query(ctx, sql, &res)
	return
}

var ProjectID = func(ctx context.Context, pID string) (res int64, err error) {
	ds := DS(ctx)
	sql := `select * from projects where p_id=?`
	err = ds.Query(ctx, sql, &res, pID)
	return
}

var GetPIds = func(ctx context.Context, pID int64) (res []int64, err error) {
	ds := DS(ctx)
	sql := `select * from projects where p_id=?`
	err = ds.QueryAll(ctx, sql, &res, pID)
	return
}

var GetPID = func(ctx context.Context, pID int64) (res int64, err error) {
	ds := DS(ctx)
	sql := `select * from projects where p_id=?`
	err = ds.Query(ctx, sql, &res, pID)
	return
}
