package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/internal/no_orm/dbal/dto"
)

// (C)RUD: tasks
// Generated/AI values are passed to DTO/model.

var CreateTask = func(ctx context.Context, item *dto.Task) error {
	ds := DS(ctx)
	sql := `insert into tasks (p_id, t_priority, t_date, t_subject, t_comments) values (?, ?, ?, ?, ?)`
	row, err := ds.Insert(ctx, sql, "t_id", item.PID, item.TPriority, item.TDate, item.TSubject, item.TComments)
	if err == nil {
		err = SetRes(&item.TID, row)
	}
	return err
}

// C(R)UD: tasks

var ReadTaskList = func(ctx context.Context) (res []*dto.Task, err error) {
	ds := DS(ctx)
	sql := `select * from tasks`
	errMap := make(map[string]int)
	_onRow := func(row map[string]interface{}) {
		item := dto.Task{}
		SetInt64(&item.TID, row, "t_id", errMap)
		SetInt64(&item.PID, row, "p_id", errMap)
		SetInt64(&item.TPriority, row, "t_priority", errMap)
		SetString(&item.TDate, row, "t_date", errMap)
		SetString(&item.TSubject, row, "t_subject", errMap)
		SetString(&item.TComments, row, "t_comments", errMap)
		res = append(res, &item)
	}
	err = ds.QueryAllRows(ctx, sql, _onRow)
	if err == nil {
		err = ErrMapToErr(errMap)
	}
	return
}

// C(R)UD: tasks

var ReadTask = func(ctx context.Context, tID int64) (*dto.Task, error) {
	ds := DS(ctx)
	sql := `select * from tasks where t_id=?`
	row, err := ds.QueryRow(ctx, sql, tID)
	if err != nil {
		return nil, err
	}
	item := dto.Task{}
	errMap := make(map[string]int)
	SetInt64(&item.TID, row, "t_id", errMap)
	SetInt64(&item.PID, row, "p_id", errMap)
	SetInt64(&item.TPriority, row, "t_priority", errMap)
	SetString(&item.TDate, row, "t_date", errMap)
	SetString(&item.TSubject, row, "t_subject", errMap)
	SetString(&item.TComments, row, "t_comments", errMap)
	err = ErrMapToErr(errMap)
	return &item, err
}

// CR(U)D: tasks

var UpdateTask = func(ctx context.Context, item *dto.Task) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `update tasks set p_id=?, t_priority=?, t_date=?, t_subject=?, t_comments=? where t_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.PID, item.TPriority, item.TDate, item.TSubject, item.TComments, item.TID)
	return
}

// CRU(D): tasks

var DeleteTask = func(ctx context.Context, item *dto.Task) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `delete from tasks where t_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.TID)
	return
}

var ReadByProject = func(ctx context.Context, pID int64) (res []*dto.TaskLi, err error) {
	ds := DS(ctx)
	sql := `select t_id, t_priority, t_date, t_subject from tasks where p_id =? 
		order by t_id`
	errMap := make(map[string]int)
	_onRow := func(row map[string]interface{}) {
		item := dto.TaskLi{}
		SetInt64(&item.TID, row, "t_id", errMap)
		SetInt64(&item.TPriority, row, "t_priority", errMap)
		SetString(&item.TDate, row, "t_date", errMap)
		SetString(&item.TSubject, row, "t_subject", errMap)
		res = append(res, &item)
	}
	err = ds.QueryAllRows(ctx, sql, _onRow, pID)
	if err == nil {
		err = ErrMapToErr(errMap)
	}
	return
}

var DelByProject = func(ctx context.Context, pID string) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `delete from tasks where p_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, pID)
	return
}

var GetCount = func(ctx context.Context) (res int64, err error) {
	ds := DS(ctx)
	sql := `select count(*) from tasks`
	err = ds.Query(ctx, sql, &res)
	return
}

var GetProjectTasks2 = func(ctx context.Context, gID string) (res []*dto.TaskLi, err error) {
	ds := DS(ctx)
	sql := `delete from tasks where p_id=?`
	errMap := make(map[string]int)
	_onRow := func(row map[string]interface{}) {
		item := dto.TaskLi{}
		SetInt64(&item.TID, row, "t_id", errMap)
		SetInt64(&item.TPriority, row, "t_priority", errMap)
		SetString(&item.TDate, row, "t_date", errMap)
		SetString(&item.TSubject, row, "t_subject", errMap)
		res = append(res, &item)
	}
	err = ds.QueryAllRows(ctx, sql, _onRow, gID)
	if err == nil {
		err = ErrMapToErr(errMap)
	}
	return
}

var GetTask = func(ctx context.Context, gID string) (*dto.Task, error) {
	ds := DS(ctx)
	sql := `delete from tasks where p_id=?`
	row, err := ds.QueryRow(ctx, sql, gID)
	if err != nil {
		return nil, err
	}
	item := dto.Task{}
	errMap := make(map[string]int)
	SetInt64(&item.TID, row, "t_id", errMap)
	SetInt64(&item.PID, row, "p_id", errMap)
	SetInt64(&item.TPriority, row, "t_priority", errMap)
	SetString(&item.TDate, row, "t_date", errMap)
	SetString(&item.TSubject, row, "t_subject", errMap)
	SetString(&item.TComments, row, "t_comments", errMap)
	err = ErrMapToErr(errMap)
	return &item, err
}
