package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/internal/sqlx/dbal/dto"
)

// (C)RUD: projects
// Generated/AI values are passed to DTO/model.

var CreateProject = func(ctx context.Context, item *dto.Project) error {
	ds := DS(ctx)
	sql := `insert into projects (p_name) values (?)`
	row, err := ds.Insert(ctx, sql, "p_id", item.PName)
	if err == nil {
		err = SetRes(&item.PID, row)
	}
	return err
}

// C(R)UD: projects

var ReadProject = func(ctx context.Context, pID int64) (*dto.Project, error) {
	ds := DS(ctx)
	sql := `select * from projects where p_id=?`
	res := &dto.Project{}
	err := ds.Select(ctx, sql, res, pID)
	if err == nil {
		return res, nil
	}
	return nil, err
}

// CR(U)D: projects

var UpdateProject = func(ctx context.Context, item *dto.Project) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `update projects set p_name=? where p_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.PName, item.PID)
	return
}

// CRU(D): projects

var DeleteProject = func(ctx context.Context, item *dto.Project) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `delete from projects where p_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.PID)
	return
}

var GetProjects = func(ctx context.Context) (res []*dto.ProjectLi, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.Select(ctx, sql, &res)
	return
}

var GetProjectIds = func(ctx context.Context) (res []int64, err error) {
	ds := DS(ctx)
	sql := `select p.*, 
		(select count(*) from tasks where p_id=p.p_id) as p_tasks_count 
		from projects p 
		order by p.p_id`
	err = ds.QueryAll(ctx, sql, &res)
	return
}
