package dbal

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

import (
	"context"
	"sdm_demo_todolist/internal/sqlx/dbal/dto"
)

// (C)RUD: tasks
// Generated/AI values are passed to DTO/model.

var CreateTask = func(ctx context.Context, item *dto.Task) error {
	ds := DS(ctx)
	sql := `insert into tasks (p_id, t_priority, t_date, t_subject, t_comments) values (?, ?, ?, ?, ?)`
	row, err := ds.Insert(ctx, sql, "t_id", item.PID, item.TPriority, item.TDate, item.TSubject, item.TComments)
	if err == nil {
		err = SetRes(&item.TID, row)
	}
	return err
}

// C(R)UD: tasks

var ReadTaskList = func(ctx context.Context) (res []*dto.Task, err error) {
	ds := DS(ctx)
	sql := `select * from tasks`
	err = ds.Select(ctx, sql, &res)
	return
}

// C(R)UD: tasks

var ReadTask = func(ctx context.Context, tID int64) (*dto.Task, error) {
	ds := DS(ctx)
	sql := `select * from tasks where t_id=?`
	res := &dto.Task{}
	err := ds.Select(ctx, sql, res, tID)
	if err == nil {
		return res, nil
	}
	return nil, err
}

// CR(U)D: tasks

var UpdateTask = func(ctx context.Context, item *dto.Task) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `update tasks set p_id=?, t_priority=?, t_date=?, t_subject=?, t_comments=? where t_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.PID, item.TPriority, item.TDate, item.TSubject, item.TComments, item.TID)
	return
}

// CRU(D): tasks

var DeleteTask = func(ctx context.Context, item *dto.Task) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `delete from tasks where t_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, item.TID)
	return
}

var GetGroupTasks = func(ctx context.Context, gID int64) (res []*dto.TaskLi, err error) {
	ds := DS(ctx)
	sql := `select t_id, t_priority, t_date, t_subject from tasks where p_id =? 
		order by t_id`
	err = ds.Select(ctx, sql, &res, gID)
	return
}

var DeleteGroupTasks = func(ctx context.Context, gID string) (rowsAffected int64, err error) {
	ds := DS(ctx)
	sql := `delete from tasks where p_id=?`
	rowsAffected, err = ds.Exec(ctx, sql, gID)
	return
}

var GetCount = func(ctx context.Context) (res int64, err error) {
	ds := DS(ctx)
	sql := `select count(*) from tasks`
	err = ds.Query(ctx, sql, &res)
	return
}

var GetGroupTasks2 = func(ctx context.Context, gID string) (res []*dto.TaskLi, err error) {
	ds := DS(ctx)
	sql := `delete from tasks where p_id=?`
	err = ds.Select(ctx, sql, &res, gID)
	return
}
